#!/bin/bash

clear
if [ "$1" = "" ];then
   cat /var/log/secure
elif [ "$1" = "-c" ];then
   echo "Failed SSH User Count"
   echo "====================="
   cat /var/log/secure | grep -c "Failed"
elif [ "$1" = "-u" ];then
   echo "Failed SSH User Password List"
   echo "============================="
   echo
   cat /var/log/secure | grep "Failed" | cut -d' ' -f11
else
   echo "This is not a valid option"
fi
echo
